# Generated by Django 3.2.16 on 2022-10-06 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 15, 56, 22, 458096, tzinfo=utc)),
        ),
    ]
